### ISSUE TITLE
"Crash" on Startup: Incompatibility with Dash Loader 

### ISSUE THREAD

**Issue by Afrocntrik** [devs-immortal/The-Aether#597] opened 2022-02-12 21:45 UTC
![image](https://user-images.githubusercontent.com/11052983/153729418-0529d126-3a79-4c8a-83f3-8160bdc4e88e.png)
[latest.log](https://github.com/devs-immortal/Paradise-Lost/files/8054574/latest.log)
Game freezes at the above image, mostly likely incompatibility with the nested Shaders mod

**Comment by Jack-Papel** [comment] 2022-02-12 21:51
Duplicate of #559.We've fixed the issue in dev builds, and it should work in the next prerelease. Thanks for reporting!

**Closed as completed by Jack-Papel** 2022-02-12 21:51 UTC
Labels: duplicate, Resolved
