### ISSUE TITLE
Bug: Can't enter Dimension on Server on Latest 1.18.2 Beta

### ISSUE THREAD

**Issue by SHXRKIEgg** [devs-immortal/The-Aether#638] opened 2022-03-25 03:07 UTC
### What happened?

You fixed the Issue of it not crashing on servers but now you cant even enter the Dimension as it doesn't exist or the portal works

### Mod Version

Beta 1.18.2 - 1.6.7

### Fabric API Version

0.13.3

### Relevant log output

```Shell
N/A
```

### Other mods

Nope

### Additional Information

N/A

**Comment by Jack-Papel** [comment] 2022-03-25 03:11
Log output is applicable. Please share it so we can fix the issue.

**Comment by Jack-Papel** [comment] 2022-03-25 03:13
Also, is this on a world created before adding paradise lost, or a world created with the mod installed?

**Comment by SHXRKIEgg** [comment] 2022-03-25 03:15
New World and the log says nothing but here https://pastebin.com/giHrWJER
It seems like it was not tested on server after fix rather just got it launching and thats it

**Comment by Jack-Papel** [comment] 2022-03-25 03:17
Can you send the log from the client?

**Comment by SHXRKIEgg** [comment] 2022-03-25 03:18
Client - https://pastebin.com/a7qrMAsn

**Comment by Jack-Papel** [comment] 2022-03-25 03:20
Oh that's strange

**Comment by SHXRKIEgg** [comment] 2022-03-25 03:22
The Dimension does not exist on server as you can just check it by the /execute in "Dimension" command, works for SP

**Comment by SHXRKIEgg** [comment] 2022-03-25 03:22
Was testing it to be added to Better Minecraft Modpack but then I made sure to test it alone first

**Comment by Jack-Papel** [comment] 2022-03-25 04:03
Alright, we think we have a clue about what the issue is. Did your nether and end dimensions work? From the log it looks like they weren't created either.

**Comment by SHXRKIEgg** [comment] 2022-03-25 05:09
> Alright, we think we have a clue about what the issue is. Did your nether and end dimensions work? From the log it looks like they weren't created either.

yeah they show up but didnt enter them though so not sure

**Comment by Jack-Papel** [comment] 2022-03-25 05:11
That actually was an unrelated thing, nevermind. Thanks for the response though.
Restarting the server seems to fix the issue. We're working on a solution that will get it right first try.

**Comment by kyrptonaught** [comment] 2022-03-25 09:02
This is actually a vanilla bug, that’s been around since 1.16 when datapack dinensions were added. It went unnoticed since Fabric Api had a fix bundled with it. 1.18.2 broke this fix and it has not been updated yet. 

The server creates the level.dat, which contains all the available dimensions, before it loads the data packs and gets the custom dimensions from there. This causes only vanilla dimensions to be loaded. 

The good news though is that this only occurs on dedicated servers, and only on the first launch. Subsequent launches will successfully load the datapack dimensions. 

Unsure if this is worth fixing, as it’s simple enough to work around it. And a fix should be added back to FAPI soon.

**Comment by kyrptonaught** [comment] 2022-03-25 09:08
See here: https://github.com/FabricMC/fabric/blob/1.18.2/fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/mixin/dimension/ServerBugfixMixin.java

and here: 
https://bugs.mojang.com/browse/MC-195468

**Comment by gudenau** [comment] 2022-03-26 05:36
There is a temporary error condition now, hopefully the message it prints is clear enough.

**Comment by Jack-Papel** [comment] 2022-03-26 05:59
**There will be in the next update

**Comment by Jack-Papel** [comment] 2022-04-01 02:01
Resolved* in latest release

**Closed as completed by Jack-Papel** 2022-04-01 02:01 UTC
Labels: Bug, Aliquam, Not PL, Mojang
