### ISSUE TITLE
Having a piglin within render distance while wearing valkyrie armour crashes the game.

### ISSUE THREAD

**Issue by kodadacod** [devs-immortal/The-Aether#44] opened 2020-12-04 06:17 UTC
grammar

**Comment by Dragonoidzero** [comment] 2020-12-04 06:22
I... what... why?
I am going to preemptively assume this is geckolib, because it reeks of geckolib. Can you get us a crash log?

**Comment by kodadacod** [comment] 2020-12-04 17:24
here it is, and it also only seems to happen once I've rendered the armour in 3rd person.
https://pastebin.com/rU8ep4nf

**Comment by Snivyer1910** [comment] 2020-12-06 06:41
this is the most specificly stupid issue I've ever seen

**Comment by Snivyer1910** [comment] 2020-12-06 07:04
Couldn't replicate with sodium
![2020-12-06_00 59 58](https://user-images.githubusercontent.com/72054019/101273853-d0889e80-375e-11eb-92cd-b7a158935c95.png)

**Comment by CDAGaming** [comment] 2021-01-02 07:16
Closing as non-reproducable in current master branch.

**Closed by CDAGaming** 2021-01-02 07:16 UTC
Labels: Bug
