### ISSUE TITLE
Crash: crashed on startup

### ISSUE THREAD

**Issue by Nathan22211** [devs-immortal/The-Aether#678] opened 2022-05-21 19:24 UTC
### What were you doing when the crash occured? How can we replicate it?

Loading the game after adding just 2 mods, Fabric botania and fabric create. Both from curseforge.

### Did it crash the client or server?

Client

### Mod Version

1.6.8

### Fabric API Version

0.53.0

### Crash Report

```Shell
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 5/21/22, 2:14 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'the_aether'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ExceptionInInitializerError
	at net.id.aether.util.RenderUtils.auralCutoutMippedRenderLayer(RenderUtils.java:56)
	at net.id.aether.blocks.AetherBlockActions.lambda$static$7(AetherBlockActions.java:32)
	at net.id.incubus_core.util.RegistryQueue.register(RegistryQueue.java:46)
	at net.id.incubus_core.util.RegistryQueue.register(RegistryQueue.java:38)
	at net.id.aether.blocks.AetherBlocks.init(AetherBlocks.java:424)
	at net.id.aether.Aether.onInitialize(Aether.java:90)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 7 more
Caused by: java.lang.IllegalStateException: RenderLayer RenderType[solid_the_aether:aural_1927451382:CompositeState[[texture[Optional[minecraft:textures/atlas/blocks.png](blur=false, mipmap=true)], shader[Optional[ladysnake.satin.impl.ResettableManagedCoreShader$$Lambda$6654/0x0000000800ed2270@4c40b284]], no_transparency, depth_test[<=], cull[true], lightmap[true], overlay[false], no_layering, main_target, default_texturing, write_mask_state[writeColor=true, writeDepth=true], line_width[1.0]], outlineProperty=affects_outline]] was added too late.
	at ladysnake.satin.impl.BlockRenderLayerRegistry.registerRenderLayer(BlockRenderLayerRegistry.java:34)
	at ladysnake.satin.api.util.RenderLayerHelper.registerBlockRenderLayer(RenderLayerHelper.java:90)
	at net.id.aether.client.rendering.shader.AetherRenderLayers.<clinit>(AetherRenderLayers.java:26)
	... 14 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:452)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:197)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (amd64) version 5.4.0-110-generic
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1301105984 bytes (1240 MiB) / 2248146944 bytes (2144 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: unknown
	Frequency (GHz): 2.40
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: UHD Graphics 630 (Mobile)
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 512.00
	Graphics card #0 deviceId: 0x3e9b
	Graphics card #0 versionInfo: unknown
	Graphics card #1 name: GP107M [GeForce GTX 1050 3 GB Max-Q]
	Graphics card #1 vendor: NVIDIA Corporation (0x10de)
	Graphics card #1 VRAM (MB): 288.00
	Graphics card #1 deviceId: 0x1c91
	Graphics card #1 versionInfo: unknown
	Virtual memory max (MB): 9972.71
	Virtual memory used (MB): 5116.55
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 1.00
	JVM Flags: 11 total; -XX:-OmitStackTraceInFastThrow -Xms512M -Xmx4096M -XX:MetaspaceSize=256M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xss1M
	Fabric Mods: 
		alternate-current 1.2.1
		attributefix 14.0.1
		betterclouds 1.0.5+1.18.2
		botania 1.18.2-432-FABRIC
			fiber 0.23.0-2
			step-height-entity-attribute 1.0.0
		cloth-api 3.2.64
			cloth-basic-math 0.6.0
			cloth-client-events-v0 3.2.64
			cloth-common-events-v1 3.2.64
			cloth-datagen-api-v1 3.2.64
			cloth-scissors-api-v1 3.2.64
			cloth-utils-v1 3.2.64
		create mc1.18.2_v0.4.1+576
			com_electronwill_night-config_core 3.6.3
			com_electronwill_night-config_toml 3.6.3
			com_google_code_findbugs_jsr305 3.0.2
			fake-player-api 0.3.0
			flywheel 1.18-0.6.2.25
			forge_tags 2.1
			forgeconfigapiport 3.2.0
			milk 0.3.2
				dripstone_fluid_lib 1.2.0
			noindium 1.0.1+1.18.2
				omega-config 1.2.3-1.18.1
			porting_lib 1.1.0-beta+1.18.2-dev.fcf3b16
				com_github_llamalad7_mixinextras 0.0.9
				mm 2.3
			registrate-fabric MC1.18.2-1.0.3
				fabric-data-generation-api-v1 2.0.9+e19de87d60
		crops_love_rain 1.2.2
		cullleaves 2.3.2
		dawn 3.3.0
			cloth-config 6.2.57
		endstone 1.1.0
		extrasounds 2.2.1+1.18.2
			advanced_runtime_resource_pack 0.5.5
			soundcategories 1.2.1+1.18
		fabric 0.53.0+1.18.2
			fabric-api-base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1 1.6.0+2373a54560
			fabric-biome-api-v1 8.0.4+7b0f312660
			fabric-blockrenderlayer-v1 1.1.12+3ac43d9560
			fabric-command-api-v1 1.1.9+d7c144a860
			fabric-commands-v0 0.2.8+b4f4f6cd60
			fabric-containers-v0 0.1.21+d7c144a860
			fabric-content-registries-v0 3.0.4+d82b939260
			fabric-convention-tags-v1 1.0.1+474e4f7960
			fabric-crash-report-info-v1 0.2.0+a6b0947860
			fabric-dimensions-v1 2.1.17+2540745460
			fabric-entity-events-v1 1.4.8+d7c144a860
			fabric-events-interaction-v0 0.4.19+d7c144a860
			fabric-events-lifecycle-v0 0.2.15+d7c144a860
			fabric-game-rule-api-v1 1.0.13+d7c144a860
			fabric-item-api-v1 1.5.0+85719ab760
			fabric-item-groups-v0 0.3.12+91896a4960
			fabric-key-binding-api-v1 1.0.12+54e5b2ec60
			fabric-keybindings-v0 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1 2.0.3+2d83e92c60
			fabric-loot-tables-v1 1.0.11+d7c144a860
			fabric-mining-level-api-v1 2.1.1+81ea5b3c60
			fabric-models-v0 0.3.6+d7c144a860
			fabric-networking-api-v1 1.0.21+d882b91560
			fabric-networking-v0 0.3.8+b4f4f6cd60
			fabric-object-builder-api-v1 2.1.1+032c981d60
			fabric-particles-v1 0.2.12+526dc1ac60
			fabric-registry-sync-v0 0.9.8+0d9ab37260
			fabric-renderer-api-v1 0.4.13+d882b91560
			fabric-renderer-indigo 0.5.0+7faf0d8860
			fabric-renderer-registries-v1 3.2.11+b4f4f6cd60
			fabric-rendering-data-attachment-v1 0.3.7+d7c144a860
			fabric-rendering-fluids-v1 2.0.2+54e5b2ec60
			fabric-rendering-v0 1.1.13+b4f4f6cd60
			fabric-rendering-v1 1.10.7+54e5b2ec60
			fabric-resource-conditions-api-v1 2.0.3+91b7aa6660
			fabric-resource-loader-v0 0.5.0+2afceb2960
			fabric-screen-api-v1 1.0.10+d882b91560
			fabric-screen-handler-api-v1 1.2.0+1f6558e860
			fabric-textures-v0 1.0.12+3ac43d9560
			fabric-transfer-api-v1 1.6.1+f4563ac860
			fabric-transitive-access-wideners-v1 1.0.0+bd8a4a1860
		fabricloader 0.14.6
		here-be-no-dragons 1.0.0
		java 17
		kiln 1.0.0
		minecraft 1.18.2
		nbtcrafting 2.1.3+mc1.18.2
		patchouli 1.18.2-67-FABRIC
		presencefootsteps 1.5.0
			kirin 1.10.0
		promenade 2.6.1
			terraform-shapes-api-v1 2.1.0
		puddles 1.2.1
		rocks 1.6.0
			midnightlib 0.4.0
		snowytrees 1.1.0
		taxfreelevels 1.3
		the_aether 1.6.8+1.18.2
			cardinal-components-base 4.1.3
			cardinal-components-entity 4.1.3
			crowdin-translate 1.4+1.18.2
			customportalapi 0.0.1-beta50-1.18
			gud_recipe_confidence 1.0.2
			incubus_core 1.6.6+1.18.2
			moretags 3.0.3
			reach-entity-attributes 2.1.1
			satin 1.7.2
		trinkets 3.3.1
		twigs 1.1.3-patch1+1.18.2
		visuality 0.4.2
			goosik-config 0.2.0
			tlcosmetica 0.4.0
		wandering_collector 1.1.2+mc1.18.2
			coat 1.0.0-beta.17+mc1.18.2
			tweed4_annotated 1.3.0
			tweed4_base 1.5.0+mc1.18.2
			tweed4_data 1.2.1+mc1.18.2
			tweed4_data_hjson 1.1.0
			tweed4_tailor_coat 1.1.2+mc1.18.2
			tweed4_tailor_screen 1.1.1+mc1.18.2
		waterdripsound 1.18-0.3.0
		worldspecificviewdistance 0.1.0-1.18
	Flywheel Backend: Uninitialized
	Launched Version: 1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
```

### Other mods

I was using a multitude of others, but the last ones I remember adding were botania and create. So I can narrow it down to something with either of those 2

### Additional Information

I'm using the ATL launcher on Linux Mint. From Mamory, I can narrow it down to it happening after I added botania and create

**Comment by Jack-Papel** [comment] 2022-05-21 19:38
Thanks for reporting. This is a duplicate of #667.

**Comment by Shadow3641** [comment] 2022-05-25 23:21
I got the same issue when i installed create

**Closed as completed** 2022-05-30 23:52 UTC
Labels: Bug, duplicate, Incompatibility
