### ISSUE TITLE
Bug: Farmer's Delight conflict

### ISSUE THREAD

**Issue by re11ding** [devs-immortal/The-Aether#623] opened 2022-03-11 19:06 UTC
### What happened?

It seems that if both Farmer's Delight and Paradise Lost is installed as mods, Paradise Lost will prevent the player from being able to plant things on Farmer's Delight's Rich Soil block. While unknown if it matters or not, this happens specifically in the Better Minecraft Modpack for 1.18.1 (Fabric). It may still occur with just these two mods, however.

To recreate the bug, simply have both mods installed, place a Rich Soil block from Farmer's Delight, Hoe it, and attempt to plant something on it. You will not be able to plant it. However, if the Paradise Lost mod is disabled, planting works as expected.

### Mod Version

1.6.5 - 1.18

### Fabric API Version

0.13.3

### Relevant log output

```
[14:15:31] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.13.3
[14:15:32] [main/INFO]: Loading 61 mods:
	- cardinal-components-base 4.0.1 via the_aether
	- cardinal-components-entity 4.0.1 via the_aether
	- crowdin-translate 1.3+1.17 via the_aether
	- customportalapi 0.0.1-beta49-1.18 via the_aether
	- fabric 0.46.6+1.18
	- fabric-api-base 0.4.2+d7c144a865 via fabric
	- fabric-api-lookup-api-v1 1.5.3+d7c144a865 via fabric
	- fabric-biome-api-v1 6.0.2+d7c144a865 via fabric
	- fabric-blockrenderlayer-v1 1.1.10+3ac43d9565 via fabric
	- fabric-command-api-v1 1.1.7+d7c144a865 via fabric
	- fabric-commands-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-containers-v0 0.1.19+d7c144a865 via fabric
	- fabric-content-registries-v0 0.4.9+d7c144a865 via fabric
	- fabric-crash-report-info-v1 0.1.9+3ac43d9565 via fabric
	- fabric-dimensions-v1 2.1.10+a1d9bbf565 via fabric
	- fabric-entity-events-v1 1.4.6+d7c144a865 via fabric
	- fabric-events-interaction-v0 0.4.17+d7c144a865 via fabric
	- fabric-events-lifecycle-v0 0.2.9+d7c144a865 via fabric
	- fabric-game-rule-api-v1 1.0.11+d7c144a865 via fabric
	- fabric-item-api-v1 1.3.1+691a79b565 via fabric
	- fabric-item-groups-v0 0.3.7+3ac43d9565 via fabric
	- fabric-key-binding-api-v1 1.0.9+d7c144a865 via fabric
	- fabric-keybindings-v0 0.2.7+b4f4f6cd65 via fabric
	- fabric-lifecycle-events-v1 1.4.13+713c266865 via fabric
	- fabric-loot-tables-v1 1.0.9+d7c144a865 via fabric
	- fabric-mining-level-api-v1 1.0.7+d7c144a865 via fabric
	- fabric-mining-levels-v0 0.1.12+b4f4f6cd65 via fabric
	- fabric-models-v0 0.3.4+d7c144a865 via fabric
	- fabric-networking-api-v1 1.0.19+d7c144a865 via fabric
	- fabric-networking-v0 0.3.6+b4f4f6cd65 via fabric
	- fabric-object-builder-api-v1 1.11.5+737332ce65 via fabric
	- fabric-object-builders-v0 0.7.13+d7c144a865 via fabric
	- fabric-particles-v1 0.2.10+526dc1ac65 via fabric
	- fabric-registry-sync-v0 0.9.2+ad01bfbd65 via fabric
	- fabric-renderer-api-v1 0.4.11+b0b66fc365 via fabric
	- fabric-renderer-indigo 0.4.15+6825030165 via fabric
	- fabric-renderer-registries-v1 3.2.10+b4f4f6cd65 via fabric
	- fabric-rendering-data-attachment-v1 0.3.5+d7c144a865 via fabric
	- fabric-rendering-fluids-v1 0.1.19+3ac43d9565 via fabric
	- fabric-rendering-v0 1.1.12+b4f4f6cd65 via fabric
	- fabric-rendering-v1 1.10.6+713c266865 via fabric
	- fabric-resource-conditions-api-v1 1.0.2+d7c144a865 via fabric
	- fabric-resource-loader-v0 0.4.15+8906aafd65 via fabric
	- fabric-screen-api-v1 1.0.8+d7c144a865 via fabric
	- fabric-screen-handler-api-v1 1.1.12+d7c144a865 via fabric
	- fabric-structure-api-v1 2.1.3+d7c144a865 via fabric
	- fabric-tag-extensions-v0 1.2.9+d7c144a865 via fabric
	- fabric-textures-v0 1.0.10+3ac43d9565 via fabric
	- fabric-tool-attribute-api-v1 1.3.9+fb3b57b465 via fabric
	- fabric-transfer-api-v1 1.5.10+c329913d65 via fabric
	- fabricloader 0.13.3
	- farmersdelight 1.18.1-0.2.0
	- gud_csl 1.0.0 via the_aether
	- gud_recipe_confidence 1.0.2 via the_aether
	- incubus_core 1.6.6+1.18.1 via the_aether
	- java 17
	- minecraft 1.18.1
	- moretags 2.0.2 via the_aether
	- reach-entity-attributes 2.1.1 via the_aether
	- the_aether 1.6.5.3+1.18.1
	- trinkets 3.1.0 via the_aether
[14:15:32] [main/WARN]: Mod `the_aether` (1.6.5.3+1.18.1) uses more dot-separated version components than SemVer allows; support for this is currently not guaranteed.
[14:15:32] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/D:/Users/re11d/Desktop/MultiMC/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[14:15:32] [main/INFO]: Compatibility level set to JAVA_16
[14:15:32] [main/INFO]: Compatibility level set to JAVA_17
[14:15:38] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$zeh000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[14:15:40] [main/WARN]: @Inject(@At("INVOKE_ASSIGN")) Shift.BY=2 on gud_recipe_confidence.mixins.json:IngredientMixin::handler$zko002$init exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[14:15:42] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[14:15:43] [Render thread/INFO]: Setting user: re11ding
[14:15:45] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[14:15:46] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[14:15:51] [Render thread/INFO]: Narrator library for x64 successfully loaded
[14:15:52] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Custom Portal Api, Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Command API (v1), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Crash Report Info (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot Tables (v1), Fabric Mining Level API (v1), Fabric Mining Levels (v0), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Object Builders (v0), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Structure API (v1), Fabric Tag Extensions (v0), Fabric Textures (v0), Fabric Tool Attribute API (v1), Fabric Transfer API (v1), Fabric Loader, Farmer's Delight, Custom Shader Lib, Recipe Confidence, Incubus Core, More Tags, Reach Entity Attributes, Paradise Lost - The Aether Reborn, Trinkets)
[14:15:52] [Render thread/INFO]: [STDOUT]: Inject generated resource packs.
[14:15:59] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on HeadPhone/Digital Output (Realtek High Definition Audio)
[14:15:59] [Render thread/INFO]: Sound engine started
[14:15:59] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[14:15:59] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[14:15:59] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[14:15:59] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[14:15:59] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/chest.png-atlas
[14:15:59] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[14:15:59] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[14:16:01] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[14:16:01] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[14:16:01] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[14:16:09] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[14:16:09] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[14:16:09] [Render thread/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[14:16:09] [Render thread/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[14:16:09] [Render thread/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[14:16:09] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Tool Attribute API (v1), Farmer's Delight, Incubus Core, More Tags, Paradise Lost - The Aether Reborn, Trinkets)
[14:16:10] [Render thread/INFO]: Loaded 9 recipes
[14:16:10] [Render thread/INFO]: Loaded 1282 advancements
[14:16:11] [Render thread/INFO]: [fabric-registry-sync] Loaded registry data [file 1/4]
[14:16:13] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[14:16:13] [Render thread/INFO]: Applied 100 biome modifications to 58 of 68 new biomes in 25.83 ms
[14:16:13] [Server thread/INFO]: Starting integrated minecraft server version 1.18.1
[14:16:13] [Server thread/INFO]: Generating keypair
[14:16:14] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[14:16:15] [Render thread/INFO]: Preparing spawn area: 0%
[14:16:15] [Render thread/INFO]: Preparing spawn area: 0%
[14:16:15] [Render thread/INFO]: Preparing spawn area: 0%
[14:16:15] [Render thread/INFO]: Preparing spawn area: 0%
[14:16:21] [Render thread/INFO]: Preparing spawn area: 0%
[14:16:21] [Render thread/INFO]: Preparing spawn area: 0%
[14:16:21] [Render thread/INFO]: Preparing spawn area: 0%
[14:16:21] [Render thread/INFO]: Preparing spawn area: 0%
[14:16:21] [Render thread/INFO]: Preparing spawn area: 0%
[14:16:21] [Render thread/INFO]: Preparing spawn area: 0%
[14:16:21] [Render thread/INFO]: Preparing spawn area: 0%
[14:16:21] [Render thread/INFO]: Preparing spawn area: 0%
[14:16:21] [Render thread/INFO]: Preparing spawn area: 0%
[14:16:21] [Render thread/INFO]: Preparing spawn area: 0%
[14:16:21] [Render thread/INFO]: Preparing spawn area: 0%
[14:16:21] [Render thread/INFO]: Preparing spawn area: 0%
[14:16:22] [Render thread/INFO]: Preparing spawn area: 0%
[14:16:22] [Render thread/INFO]: Preparing spawn area: 4%
[14:16:23] [Render thread/INFO]: Preparing spawn area: 8%
[14:16:23] [Render thread/INFO]: Preparing spawn area: 15%
[14:16:24] [Render thread/INFO]: Preparing spawn area: 22%
[14:16:24] [Render thread/INFO]: Preparing spawn area: 28%
[14:16:25] [Render thread/INFO]: Preparing spawn area: 33%
[14:16:25] [Render thread/INFO]: Preparing spawn area: 40%
[14:16:26] [Render thread/INFO]: Preparing spawn area: 44%
[14:16:26] [Render thread/INFO]: Preparing spawn area: 56%
[14:16:27] [Render thread/INFO]: Preparing spawn area: 65%
[14:16:27] [Render thread/INFO]: Preparing spawn area: 79%
[14:16:28] [Render thread/INFO]: Preparing spawn area: 86%
[14:16:28] [Render thread/INFO]: Preparing spawn area: 92%
[14:16:30] [Render thread/INFO]: Time elapsed: 16285 ms
[14:16:30] [Server thread/INFO]: Changing view distance to 12, from 10
[14:16:30] [Server thread/INFO]: Changing simulation distance to 12, from 0
[14:16:34] [Server thread/INFO]: re11ding[local:E:0005e283] logged in with entity id 252 at (-0.489958942693223, 70.0, -4.997798414472514)
[14:16:34] [Server thread/INFO]: re11ding joined the game
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/red_mushroom_colony
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/warped_trapdoor
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/oak_door
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/warped_door
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/spruce_log
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/dark_oak_log
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cooking/farmersdelight:cooking/beetroot_soup
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cooking/farmersdelight:cooking/chicken_soup
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/ham
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/dark_oak_door
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/saddle
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/birch_wood
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/beef
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/cod
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cooking/farmersdelight:cooking/stuffed_pumpkin_block
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cooking/farmersdelight:cooking/pasta_with_meatballs
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/smoked_ham
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cooking/farmersdelight:cooking/beef_stew
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/dark_oak_wood
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/birch_sign
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/sweet_berry_cheesecake
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cooking/farmersdelight:cooking/rabbit_stew
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/birch_log
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/warped_sign
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/jungle_sign
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/acacia_door
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cooking/farmersdelight:cooking/cooked_rice
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/bricks
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/apple_pie
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cooking/farmersdelight:cooking/vegetable_noodles
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/jungle_door
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cooking/farmersdelight:cooking/fried_rice
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/cake
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/acacia_log
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/cooked_chicken
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/oak_trapdoor
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/spruce_sign
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/crimson_trapdoor
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cooking/farmersdelight:cooking/pasta_with_mutton_chop
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/cooked_salmon
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/acacia_sign
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/melon
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/spruce_door
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/oak_wood
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/crimson_hyphae
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/cooked_mutton
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cooking/farmersdelight:cooking/hot_cocoa
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/birch_trapdoor
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/oak_sign
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cooking/farmersdelight:cooking/fish_stew
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/clay
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cooking/farmersdelight:cooking/vegetable_soup
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/warped_hyphae
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/leather_chestplate
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cooking/farmersdelight:cooking/pumpkin_soup
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/crimson_stem
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/acacia_trapdoor
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/birch_door
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/pumpkin
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cooking/farmersdelight:cooking/noodle_soup
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/chicken
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/jungle_wood
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/salmon
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/leather_helmet
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/jungle_trapdoor
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cooking/farmersdelight:cooking/dog_food
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/porkchop
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/acacia_wood
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/leather_leggings
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cooking/farmersdelight:cooking/dumplings
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/mutton
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cooking/farmersdelight:cooking/mushroom_stew
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/crimson_sign
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/spruce_trapdoor
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/oak_log
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/spruce_wood
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/nether_bricks
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cooking/farmersdelight:cooking/baked_cod_stew
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/cooked_cod
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cooking/farmersdelight:cooking/cabbage_rolls
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/brown_mushroom_colony
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/chocolate_pie
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/rice_panicle
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cooking/farmersdelight:cooking/squid_ink_pasta
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cooking/farmersdelight:cooking/tomato_sauce
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/crimson_door
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/dark_oak_sign
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/jungle_log
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/leather_boots
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cooking/farmersdelight:cooking/ratatouille
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/warped_stem
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/dark_oak_trapdoor
[14:16:35] [Render thread/WARN]: Unknown recipe category: farmersdelight:cutting/farmersdelight:cutting/cabbage
[14:16:36] [Render thread/INFO]: Loaded 10 advancements
[14:17:00] [Server thread/INFO]: Saving and pausing game...
[14:17:00] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[14:17:00] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[14:17:00] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[14:17:00] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/the_aether:the_aether
[14:17:01] [Server thread/INFO]: re11ding lost connection: Disconnected
[14:17:01] [Server thread/INFO]: re11ding left the game
[14:17:01] [Server thread/INFO]: Stopping singleplayer server as player logged out
[14:17:01] [Server thread/INFO]: Stopping server
[14:17:01] [Server thread/INFO]: Saving players
[14:17:01] [Server thread/INFO]: Saving worlds
[14:17:01] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[14:17:01] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[14:17:01] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[14:17:01] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/the_aether:the_aether
[14:17:01] [Server thread/INFO]: ThreadedAnvilChunkStorage (New World): All chunks are saved
[14:17:01] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[14:17:01] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[14:17:01] [Server thread/INFO]: ThreadedAnvilChunkStorage (the_aether): All chunks are saved
[14:17:01] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[14:17:03] [Render thread/INFO]: Stopping!

```

**Comment by Jack-Papel** [comment] 2022-03-11 19:08
Can you send us a log? They can be found in `.minecraft\logs\latest.log`

**Comment by re11ding** [comment] 2022-03-11 19:09
> Can you send us a log? They can be found in `.minecraft\logs\latest.log`
Would you like a log of it loading with the whole modpack, or just the two mods?

**Comment by Jack-Papel** [comment] 2022-03-11 19:10
The latter is preferable

**Comment by re11ding** [comment] 2022-03-11 19:18
I have updated the original post with the appropriate log file!

**Comment by Jack-Papel** [comment] 2022-03-11 19:21
Alright, thanks

**Comment by Jack-Papel** [comment] 2022-03-12 04:59
@gudenau, looks like this is caused by moretags [here](https://github.com/gudenau/minecraft-MoreTags/blob/1685e365c53f4f9c7d420d74ffefc2f99feb5e23/src/main/java/net/gudenau/minecraft/moretags/mixins/farmland/PlantBlockMixin.java#L20). "Overrides" farmer's delight's impl [here](https://bitbucket.org/n-horyzon/farmers-delight-fabric/src/62d2c9c00612c5da3ee3a52d59a1f8c7a068a114/src/main/java/com/nhoryzon/mc/farmersdelight/mixin/AttachedStemBlockOnRichSoilFarmlandMixin.java#lines-14).
Mind you, this is a primarily forge mod with a fabric port, so they may not be so open to adopting your dependency. I would recommend changing your redirect to do a similar thing their inject does.

**Comment by KMFrench1** [comment] 2022-03-13 15:56
Could this be fixed with a datapack? as a temporary solution

**Comment by KMFrench1** [comment] 2022-03-13 16:16
Well, Making a data pack let me plant the seeds. However, it does not act like rich soil, it acts like regular farmland. Maybe @gudenau can add a new tag type that does the random bonemeal thing that rich soil does?

**Comment by Jack-Papel** [comment] 2022-03-24 16:29
@gudenau reminder

**Closed as completed** 2022-12-06 01:25 UTC
Labels: Bug, dependency, Resolved, Incompatibility
