### ISSUE TITLE
Bug: Rose Wisteria Leaves despawning, (possibly) causing stutters

### ISSUE THREAD

**Issue by YurgenSchn** [devs-immortal/The-Aether#595] opened 2022-02-09 01:18 UTC
### What happened?

I was roaming around the Aether dimension, and i found this cool sakura like tree. The moment i approached it, my game started stuttering lightly as some of its leave blocks started to dissapear. Not all of them, just some of the outter ones farther from log blocks.

I've seen this happen with the Terralith worldgen datapack/mod, and i think it's due to naturally generated Wisteria Leaves despawning and taking down the Rose Wisteria Hangers with them. Can't comment on the technicallity of the stutter, but they feel related, so maybe block and lighting updates?

![image](https://user-images.githubusercontent.com/42218362/153103433-1251c1ed-1e57-4701-ad50-96bdd0ee1eea.png)

### Mod Version

1.6.5 - 1.18

### Fabric API Version

0.46.1

**Comment by CDAGaming** [comment] 2022-02-09 01:20
This is indeed due to an issue in wisteria trees, and them somehow decaying prematurly without intervention. Combine this with a whole biome of rose wisteria, and it would indeed cause major lag. We'll look into this for the full release.

**Comment by gudenau** [comment] 2022-02-17 04:54
![image](https://user-images.githubusercontent.com/5642329/154408005-954acf82-aec9-433b-b2b6-b9316d28ed3d.png)
Can not reproduce.

**Comment by Jack-Papel** [comment] 2022-03-25 20:00
Resolved on b1.7 branch. Change needs to be ported to 1.18.2

**Comment by MBatt1** [comment] 2022-03-25 21:22
Resolved on 1.18.2

**Comment by Jack-Papel** [comment] 2022-04-01 02:04
Resolved in latest release. Thanks for reporting

**Closed as completed by Jack-Papel** 2022-04-01 02:04 UTC
Labels: Bug, Priority, Resolved
