### ISSUE TITLE
Portal not working!!!

### ISSUE THREAD

**Issue by RailX1** [devs-immortal/The-Aether#612] opened 2022-02-23 08:02 UTC
### What happened?

he animation goes along with the sound, but the portal doesn't work.
I tried to play without other mods, it did not help
(Maybe the portal does not work well with worlds that were created before installing).
https://www.youtube.com/watch?v=U3udsIqGWI4

### Mod Version

1.6.5 - 1.18

### Fabric API Version

last

### Additional Information

https://www.youtube.com/watch?v=U3udsIqGWI4

**Comment by Jack-Papel** [comment] 2022-03-25 20:18
The video has been removed, and you need to provide log output

**Comment by Jack-Papel** [comment] 2022-03-25 20:18
Based on the title and caption, this has likely been resolved by the latest release. Let us know.

**Comment by Jack-Papel** [comment] 2022-03-29 16:55
Likely a duplicate of #638

**Comment by Jack-Papel** [comment] 2022-05-01 03:03
#638 has been resolved, so this is likely resolved too.

**Closed as completed by Jack-Papel** 2022-05-01 03:03 UTC
Labels: Bug, duplicate, Priority, More Info Required
