### ISSUE TITLE
Gravitite missing texture and crashes game when worn.

### ISSUE THREAD

**Issue by toErIpNid** [devs-immortal/The-Aether#193] opened 2021-04-20 01:28 UTC
crash log: [crash-2021-04-19_20.23.47-client.txt](https://github.com/devs-immortal/The-Aether/files/6339950/crash-2021-04-19_20.23.47-client.txt)

game version: 1.16.5

mod version: 1.0.2

fabric version: 0.11.3

**Comment by Jack-Papel** [comment] 2021-04-20 03:00
This is a known issue. Duplicate of #133 and #67.

**Comment by MBatt1** [comment] 2021-04-21 22:44
Armor textures are WIP, however gravitite armor no longer crashes the game in the dev build, but I still gotta do the texture

**Comment by MBatt1** [comment] 2021-04-22 03:13
partially resolved in b1.0.3

**Closed by MBatt1** 2021-04-22 03:13 UTC
