### ISSUE TITLE
On 1.17, you can make aether portals from The End

### ISSUE THREAD

**Issue by ruvaldak** [devs-immortal/The-Aether#397] opened 2021-07-18 23:11 UTC
Going through them can lead to many rendering and lighting problems, most especially affecting shader mods. This can be fixed by going back to the OW, then back into the Aether.

I'm using the latest Aether Reborn from CF on Fabric in 1.17.1.

**Comment by SollyW** [comment] 2021-07-18 23:22
Duplicate of #382

**Comment by ruvaldak** [comment] 2021-07-19 01:10
> Duplicate of #382

I admit, I didn't use the search function. My bad. However, I do feel the graphical problems it cause is worth noting. Granted, "easy" fix; just don't allow aether portals in the end, and there won't be graphical problems.

**Closed as completed** 2021-11-27 06:04 UTC
Labels: Bug, duplicate, Resolved
