### ISSUE TITLE
texturepackbugs

### ISSUE THREAD

**Issue by sunny-gg95** [devs-immortal/The-Aether#227] opened 2021-05-23 12:14 UTC
![texturepack1](https://user-images.githubusercontent.com/61912148/119260015-1812c200-bbfb-11eb-9a28-46b6f32cd23a.png)
![texturepack2](https://user-images.githubusercontent.com/61912148/119260017-1b0db280-bbfb-11eb-9f7a-c5726f690919.png)

**Comment by kalucky0** [comment] 2021-05-23 12:25
Duplicate of #75

**Closed by kalucky0** 2021-05-23 12:25 UTC
Labels: Resolved, duplicate
