### ISSUE TITLE
Crash: Right after starting client

### ISSUE THREAD

**Issue by TheButterbrotMan** [devs-immortal/The-Aether#654] opened 2022-04-11 12:42 UTC
### What were you doing when the crash occured? How can we replicate it?

1. First, start client.
2. Next, wait.
3. Finally, crash.

### Did it crash the client or server?

Server

### Mod Version

1.6.8+1.18.2

### Fabric API Version

0.50.0+1.18.2

### Crash Report

```Shell
https://bytebin.lucko.me/5g9yc349gF
```

### Other mods

https://www.curseforge.com/minecraft/modpacks/deathdusk

**Comment by TheButterbrotMan** [comment] 2022-04-11 12:42
https://github.com/Lemonszz/Biome-Makeover/issues/97

**Comment by TheButterbrotMan** [comment] 2022-04-11 12:56
Resolved by https://github.com/architectury/architectury-api/issues/241#issuecomment-1095009196

**Comment by TheButterbrotMan** [comment] 2022-04-11 12:57
It havent.

https://bytebin.lucko.me/KzQgUEn2Et

**Comment by netcore10** [comment] 2022-04-19 17:57
i also get it crashing on launch
[latest.log](https://github.com/devs-immortal/Paradise-Lost/files/8515317/latest.log)

**Comment by MBatt1** [comment] 2022-11-07 18:57
Appears to be a BClib incompatability, duplicate of #664

**Closed as completed by MBatt1** 2022-11-07 18:57 UTC
Labels: Bug
