### ISSUE TITLE
Crashes with OptiFabric

### ISSUE THREAD

**Issue by Page3of9** [devs-immortal/The-Aether#160] opened 2021-04-03 08:11 UTC
[crash-2021-04-03_01.09.11-client.txt](https://github.com/devs-immortal/The-Aether/files/6252146/crash-2021-04-03_01.09.11-client.txt)

**Comment by kalucky0** [comment] 2021-04-03 08:14
Duplicate of #131

**Closed** 2021-04-03 08:15 UTC
Labels: duplicate
