### ISSUE TITLE
Bug: Crashes Due to A Change in Custom Portal API

### ISSUE THREAD

**Issue by CammiePone** [devs-immortal/The-Aether#508] opened 2021-10-14 21:18 UTC
### What happened?

The game crashes upon start up due to the released version of Aether using an old version of Custom Portal API, and another mod in the pack (Atlantis) includes a newer version of it, causing Aether to crash as it can't find a class that used to exist but doesn't anymore.

### Version

1.5.0 (Latest)

### Fabric API Version

0.40.8

### Trinkets Version

3.0.4

### Relevant log output

```shell
Crash Report:
https://pastebin.com/uvVjSEWp

Log:
https://pastebin.com/HREnYGj5
```

### Other mods

```shell
- additionaladditions 2.1.3
	- advanced_runtime_resource_pack 0.2.9
	- adventure-platform-fabric 4.1.0-SNAPSHOT
	- ambientenvironment 6.0.22
	- anthropophagy 1.17-4
	- anvil_crushing_recipes 1.1.2+MC1.17-1.17.1
	- apoli 2.0.3
	- appleskin mc1.17-2.1.3
	- appletreesrev 2.5
	- aqupdcaracal 1.17-1.3.2
	- aqupdgrizzly 1.17-1.2.0
	- arcanus 1.17
	- architectury 2.5.32
	- armor-visibility 3.0.0
	- atlantis 2021.7.18-1.17-1.9.0-fabric
	- authme 1.5.0
	- autoconfig1u 3.3.1
	- automatone 0.4.1
	- axolotlitemfix 1.1.2
	- balm-fabric 1.3.0+0
	- beaconoverhaul 1.4.2+1.17
	- betterbiomeblend 1.17.0-1.2.9-fabric
	- betterdungeons 1.17-1.0.2
	- bettermineshafts 1.17-1.0.1
	- betterstrongholds 1.17-1.1.2
	- bewitchment 1.17-11
	- blockus 2.2.10+1.17.1
	- bobby 2.0.4
	- bosses_of_mass_destruction 1.2.3-1.17.1
	- caelus 0.0.17-1.17
	- calio 1.0.3
	- cardinal-components 3.1.1
	- cardinal-components-base 3.1.1
	- cardinal-components-block 3.1.1
	- cardinal-components-chunk 3.1.1
	- cardinal-components-entity 3.1.1
	- cardinal-components-item 3.1.1
	- cardinal-components-level 3.1.1
	- cardinal-components-scoreboard 3.1.1
	- cardinal-components-util 3.1.1
	- cardinal-components-world 3.1.1
	- carrier 1.8.0
	- cauldronfix 1.0.0c
	- charm 3.3.2
	- charmonium 3.3.0
	- chat_plus 2.1.5
	- chime 1.2.0-SNAPSHOT
	- chipped 1.1.1
	- cleancut 1.17-4.0-fabric
	- clear-skies 1.5.70
	- clickthrough 1.17.1-fabric0.36.1-0.4
	- cloth-api 2.0.54
	- cloth-basic-math 0.5.1
	- cloth-client-events-v0 2.0.54
	- cloth-common-events-v1 2.0.54
	- cloth-config2 5.0.38
	- cloth-datagen-api-v1 2.0.54
	- cloth-scissors-api-v1 2.0.54
	- cloth-utils-v1 2.0.54
	- cloud 1.5.0
	- cloud_commandframework_cloud-brigadier_ 1.5.0
	- cloud_commandframework_cloud-core_ 1.5.0
	- cloud_commandframework_cloud-minecraft-extras 1.5.0
	- cloud_commandframework_cloud-services_ 1.5.0
	- clumps 7.0.8
	- com_electronwill_night-config_core 3.6.4
	- com_electronwill_night-config_toml 3.6.4
	- com_flowpowered_flow-math 1.0.3
	- com_github_dimensionaldevelopment_poly2tri_java 0.1.1
	- com_moandjiezana_toml_toml4j 0.7.2
	- com_typesafe_config 1.4.1
	- com_velocitypowered_velocity-native 1.1.0-SNAPSHOT
	- combattweaks 1.0
	- confabricate 2.1.0-SNAPSHOT+4.1.1
	- config2brigadier 1.0.0
	- connectiblechains 1.2.3
	- couplings 1.5.0+1.17
	- craftablehorsearmour 1.6-Fabric
	- creeperaiupdated 1.4.0
	- crowdin-translate 1.3+1.17
	- ctm 0.5.1+1.17
	- culinaire 2.1
	- customportalapi 0.0.1-beta45-1.17
	- customsplashscreen 1.1.0
	- customstars 0.6+1.17
	- dangerousstonecutter 1.5
	- darkness 1.6.74
	- darkpaintings 4.0.2
	- dawn 2.0.6
	- defaultsettings 3.1.0
	- dimdoors 4.0.0+beta.2-26.07.2021
	- dracomelette 1.17-2
	- dungeons_arise 2.1.47-fabric
	- dynmus 1.3.1
	- easier_gunpowder 1.1.6
	- ecotones 0.8.1
	- enhancedcelestials 2.0.5
	- entityculling 1.3.3
	- extraalchemy 1.6.1
	- extraorigins 1.17-9
	- fabric 0.40.8+1.17
	- fabric-api-base 0.3.0+a02b446318
	- fabric-api-lookup-api-v1 1.3.0+cbda931818
	- fabric-biome-api-v1 3.2.0+cbda931818
	- fabric-blockrenderlayer-v1 1.1.5+a02b446318
	- fabric-command-api-v1 1.1.3+5ab9934c18
	- fabric-commands-v0 0.2.2+92519afa18
	- fabric-containers-v0 0.1.12+cbda931818
	- fabric-content-registries-v0 0.3.0+cbda931818
	- fabric-crash-report-info-v1 0.1.5+be9da31018
	- fabric-dimensions-v1 2.0.11+6cefd57718
	- fabric-entity-events-v1 1.2.3+87cc6e4c18
	- fabric-events-interaction-v0 0.4.10+fc40aa9d18
	- fabric-events-lifecycle-v0 0.2.1+92519afa18
	- fabric-game-rule-api-v1 1.0.7+cbda931818
	- fabric-item-api-v1 1.2.4+a02b446318
	- fabric-item-groups-v0 0.2.10+b7ab612118
	- fabric-key-binding-api-v1 1.0.4+cbda931818
	- fabric-keybindings-v0 0.2.2+36b77c3e18
	- fabric-language-kotlin 1.6.5+kotlin.1.5.31
	- fabric-lifecycle-events-v1 1.4.4+a02b446318
	- fabric-loot-tables-v1 1.0.4+a02b446318
	- fabric-mining-levels-v0 0.1.3+92519afa18
	- fabric-models-v0 0.3.0+a02b446318
	- fabric-networking-api-v1 1.0.13+cbda931818
	- fabric-networking-blockentity-v0 0.2.11+a02b446318
	- fabric-networking-v0 0.3.2+92519afad5
	- fabric-object-builder-api-v1 1.10.9+b7ab612118
	- fabric-object-builders-v0 0.7.3+a02b446318
	- fabric-particles-v1 0.2.4+a02b446318
	- fabric-permissions-api-v0 0.1-SNAPSHOT
	- fabric-registry-sync-v0 0.7.11+7931163218
	- fabric-renderer-api-v1 0.4.4+5f02c96918
	- fabric-renderer-indigo 0.4.8+cbda931818
	- fabric-renderer-registries-v1 3.2.4+7931163218
	- fabric-rendering-data-attachment-v1 0.1.5+a02b446318
	- fabric-rendering-fluids-v1 0.1.14+4658223018
	- fabric-rendering-v0 1.1.5+7931163218
	- fabric-rendering-v1 1.9.0+7931163218
	- fabric-resource-loader-v0 0.4.8+a00e834b18
	- fabric-screen-api-v1 1.0.4+cbda931818
	- fabric-screen-handler-api-v1 1.1.8+cbda931818
	- fabric-structure-api-v1 1.1.13+5ab9934c18
	- fabric-tag-extensions-v0 1.2.1+b06cb95b18
	- fabric-textures-v0 1.0.6+a02b446318
	- fabric-tool-attribute-api-v1 1.2.12+b7ab612118
	- fabric-transfer-api-v1 1.4.0+7931163218
	- fabricloader 0.12.1
	- fallflyinglib 3.0.0-beta.2
	- fallingleaves 1.7.3+1.17.1
	- fancymenu 2.3.4
	- fasttransferlib 0.5.6
	- fermion 2.11.241
	- fermion-modkeys 1.10.241
	- fiber 0.23.0-2
	- fiber2cloth 3.1.1
	- fireworkfrenzy 1.6
	- flytre-lib-base 1.2.0
	- flytre-lib-compat 1.0.0
	- flytre-lib-config 1.1.0
	- flytre-lib-event 1.0.1
	- flytre-lib-gui 1.0.0
	- flytre-lib-storage 2.3.1
	- flytre_lib 1.3.9
	- gbfabrictools 1.3.4+1.17
	- geckolib3 3.0.15
	- grass_pass 1.0.0
	- grindenchantments 1.4.0+1.17.1
	- haema 1.7.6+1.17
	- harvest_scythes 2.0.6
	- hologram-api 0.2.1+1.17.1
	- hookshot 20.0
	- horsestatsvanilla 4.1.8
	- icarus 1.3
	- iknowwhatimdoing 3.1.0
	- illuminations 1.9
	- impaled 1.0.1
	- impersonate 2.3.5
	- interactic 0.1.6-1.17
	- io_leangen_geantyref_geantyref 1.3.11
	- itemmodelfix 1.0.2+1.17
	- jankson 3.0.1+j1.2.0
	- java 16
	- kanos_config 0.1.4+1.14.4-1.17.1
	- konkrete 1.3.0
	- krypton 0.1.4
	- ksrch 1.0.0
	- lacrimis 2.1.3+1.17.1
	- lakeside 1.1.0+1.17
	- lambdynlights 2.0.2+1.17
	- lazydfu 0.1.2
	- libcd 3.0.3+1.16.3
	- libgui 4.0.0-beta.4+1.17-rc1
	- libninepatch 1.1.0
	- light-fix 1.0.0
	- lightoverlay 6.0.0
	- lithium 0.7.4
	- lock_minecart_view 1.2.1
	- locki 0.5.0
	- lumiwool 1.1.1
	- maelstrom_library 1.2.1-1.17-pre1
	- matrix 1.0.0
	- mavm 1.0.5
	- midnightlib 0.2.2
	- minecraft 1.17.1
	- mixintrace 1.1.0+1.17
	- mm 2.3
	- mobs_attempt_parkour 0.2.3-1.17-pre1
	- modmenu 2.0.14
	- mods-command 1.0.4
	- monsters_in_the_closet 1.0.2+1.17
	- morebannerfeatures 1.0.7
	- morevillagers-fabric 2.1.1-SNAPSHOT
	- mostructures 1.3.0-pre1-1.17.1
	- mtmechs 1.0.3
	- multipart_entities 1.1.2-1.17
	- musicdr 1.2.1
	- mythic-mounts 1.17.1-1.3
	- nears 1.1.2
	- net_kyori_adventure-api 4.8.1
	- net_kyori_adventure-key 4.8.1
	- net_kyori_adventure-platform-api 4.0.0-SNAPSHOT
	- net_kyori_adventure-serializer-configurate4 4.8.1
	- net_kyori_adventure-text-feature-pagination 4.0.0-SNAPSHOT
	- net_kyori_adventure-text-minimessage 4.2.0-SNAPSHOT
	- net_kyori_adventure-text-serializer-gson 4.8.1
	- net_kyori_adventure-text-serializer-legacy 4.8.1
	- net_kyori_adventure-text-serializer-plain 4.8.1
	- net_kyori_examination-api 1.1.0
	- net_kyori_examination-string 1.1.0
	- no-potion-offset ${version}
	- notenoughanimations 1.3.2
	- notramplefabric 1.0.0
	- observable 0.1.2-1.17
	- omega-config 1.0.8
	- onsoulfire 1.17-3
	- openloader 3.0.1
	- openworlds 1.0.3
	- org_aperlambda_lambdajcommon 1.8.1
	- org_jetbrains_kotlin_kotlin-reflect 1.5.31
	- org_jetbrains_kotlin_kotlin-stdlib 1.5.31
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.5.31
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.5.31
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.5.2
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.5.2
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.0
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.0
	- org_jgrapht_jgrapht-core 1.1.0
	- org_spongepowered_configurate-core 4.1.1
	- org_spongepowered_configurate-extra-dfu4 4.1.1
	- org_spongepowered_configurate-gson 4.1.1
	- org_spongepowered_configurate-hocon 4.1.1
	- org_spongepowered_configurate-yaml 4.1.1
	- org_yaml_snakeyaml 1.30-SNAPSHOT
	- origins 1.1.2
	- origins-classes 1.2.2
	- outvoted 2.0.0-alpha.12
	- packet_tweaker 0.2.0+1.17.1
	- pandemonium 2.0.0-alpha.12
	- pandemoniumapi 2.0.0-alpha.12
	- patchouli 1.17.1-56-FABRIC
	- pehkui 2.4.0+1.14.4-1.17.1
	- perfectaccuracy 1.1
	- piglessportals 1.1.0
	- placeholder-api 1.1.1+1.17.1
	- playerabilitylib 1.3.0
	- polymer 0.1.6+1.17.1
	- quickspyglasser 0.3.0
	- ratsmischief 1.2.2
	- reach-entity-attributes 2.1.1
	- realisticfirespread 1.17-3
	- repurposed_structures 2.3.9+1.17.1
	- requiem 2.0.0-alpha.12
	- requiem-core 2.0.0-alpha.12
	- requiemapi 2.0.0-alpha.12
	- reroll 1.3.0-1.17.1
	- respawnablepets 1.17-5
	- right-click-clear 2.0.3
	- riverredux 0.2.0
	- roughlyenoughitems 6.0.287-alpha
	- satin 1.6.4
	- scorch 1.1.2
	- seedy-behavior 1.0.1
	- server_translations_api 1.4.5+1.17
	- sgui 1.0.0-rc4+1.17.1
	- signtools 1.0.0
	- sihywtcamc 1.4.1+1.17.1
	- sihywtcamd 1.5.2+1.17.1
	- smart-recipes 0.1.0+1.17
	- smoothboot 1.16.5-1.6.0
	- snowundertrees 1.0.0
	- sodium 0.3.0+build.5
	- somnus 0.0.14-1.17.1
	- soundphysics 2.0.0
	- spruceui 3.2.0+1.17
	- starlight 1.0.0-RC3+fabric.2b7d7ae
	- statues 1.0.1
	- step-height-entity-attribute 1.0.0
	- stoneholm 1.3
	- stonevaults 1.1.0
	- sync 1.2
	- tabtps-fabric 1.3.9
	- taterzens 1.4.1
	- taxfreelevels 1.2.1
	- team_reborn_energy 2.0.0-beta1
	- terraform-biome-builder-api-v1 2.0.0
	- terraform-config-api-v1 2.0.0
	- terraform-overworld-biome-extensions-api-v1 2.0.0
	- terraform-shapes-api-v1 1.0.4
	- terraform-surfaces-api-v1 2.0.0
	- terraform-tree-api-v1 2.0.0
	- terraform-wood-api-v1 2.0.2
	- the_aether 1.17.1-1.5.0
	- things 0.2.6
	- torohealth 1.17.1-fabric-12
	- transliterationlib 1.2.2
	- traverse 4.0.0
	- tridentfixer 2.0.1
	- trinkets 3.0.4
	- universal-graves 1.1.2+1.17.1
	- urns 1.0.1
	- vehiclefix 1.1
	- villagernames 2.0.0
	- vistas 1.4.4
	- visualoverhaul 3.3.0
	- voicechat 1.17.1-1.1.4
	- voidtotem 1.17.0-1.0.0
	- waveycapes 1.0.3
	- waystones 8.1.1+0
	- what 1.0.0
	- whyamionfire 1.1.1
	- wrenchable 1.1.0+1.17
	- yungsapi 1.17-Fabric-19
```

**Comment by Jack-Papel** [comment] 2021-10-14 21:20
This is a duplicate of #506, and has been fixed in dev builds.

**Comment by CammiePone** [comment] 2021-10-17 22:44
Would be nice to have in a release build so I can update Atlantis, but ah well. From the looks of it, nearly a third of the total commits were made since the last release. Is the next release going to be the fully featured mod, or at least have nearly everything (obviously I have not read what those 400-something commits were, so idk how much of was minor fixes and how much added content)?

**Comment by Jack-Papel** [comment] 2021-10-17 22:48
Next update will add the first dungeon and lots of other exciting stuff, but the mod will not be complete. The update's projected to come out in November though, so you won't have to wait long.

**Comment by Azzyypaaras** [comment] 2021-11-27 06:02
Resolved with b1.6.0

**Closed as completed by Azzyypaaras** 2021-11-27 06:02 UTC
Labels: Bug, duplicate, Resolved
