### ISSUE TITLE
A few missing textures

### ISSUE THREAD

**Issue by Chromadon** [devs-immortal/The-Aether#224] opened 2021-05-22 00:07 UTC
Found an issue. Textures are missing from the following items:

Gravitite helmet/chestplate/legs/boots

Obsidian helmet/chest/legs/boots

Regen stone

Iron bubble

gravitate gloves

golden pendant

zanite pendant

ice pendant

Book of lore 1st edition

skyroot poison/remedy bucket

Why is this and how do I fix it

**Comment by SweepSwap** [comment] 2021-05-22 00:25
this is not a bug, and you cannot fix it. The mod is not even close to being finished yet and textures are missing, the armor, gloves, and pendants have textures on GitHub, there is just not a version on curseforge or modrinth yet.

**Comment by kalucky0** [comment] 2021-05-22 08:14
Duplicate of #75

**Closed by kalucky0** 2021-05-22 08:14 UTC
