### ISSUE TITLE
Golden Leaves dont decay

### ISSUE THREAD

**Issue by diabolical17** [devs-immortal/The-Aether#62] opened 2020-12-20 17:33 UTC

**Comment by SylisMC** [comment] 2020-12-21 18:38
(this is any leaves but skyroot)

**Comment by CDAGaming** [comment] 2021-01-02 07:44
As far as I can tell this is intended behavior, since there's a special case for this in code plus an increased distance (x2) before it can decay so I'll close this as intentional, but it can be remedied if thats what the community wants.

**Closed by CDAGaming** 2021-01-02 07:44 UTC
Labels: Bug
