### ISSUE TITLE
Floating Blocks are entirely broken

### ISSUE THREAD

**Issue by Fishiest** [devs-immortal/The-Aether#523] opened 2021-11-05 16:16 UTC
You can break bedrock, get infinite food, and hold farmland
https://youtu.be/BSPIq1fID8U

**Comment by Jack-Papel** [comment] 2021-11-05 17:14
This has been fixed in dev builds. Thanks for reporting. Let us know if you find any more bugs.

**Comment by Jack-Papel** [comment] 2021-11-05 18:08
Actually, I just watched the video and I wasn't aware of the piston thing. I'll double check that we fixed that. I appreciate the dramatic zooms too.

**Comment by Jack-Papel** [comment] 2021-11-08 01:30
Alright, now the problem is fixed 👍🏻

**Comment by Azzyypaaras** [comment] 2021-11-27 06:01
Resolved with b1.6.0

**Closed as completed by Azzyypaaras** 2021-11-27 06:01 UTC
Labels: Bug, Resolved
