### ISSUE TITLE
"I've been falling, for 30 minutes!" has incorrect trigger

### ISSUE THREAD

**Issue by UnusedCactus** [devs-immortal/The-Aether#736] opened 2022-11-25 21:47 UTC
### What happened?

The "I've been falling, for 30 minutes!" advancement is given upon entering a world for the first time with this mod installed. Previous versions of this mod would only give this advancement when the player falls from the aether.

To replicate:
Create a new world with this mod, and you will get "I've been falling, for 30 minutes!" as an advancement.

### Mod Version

v0.2.0-beta+1.19

### Fabric API Version

0.67.1+1.19.2

### Relevant log output

```Shell
[16:06:38] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2658ms or 53 ticks behind
[16:06:39] [Render thread/INFO]: New minimap session initialized!
[16:06:39] [Server thread/INFO]: UnusedCactus has made the advancement [I've been falling, for 30 minutes!]
[16:06:39] [Render thread/INFO]: New world map session initialized!
[16:06:39] [Render thread/INFO]: Started 6 worker threads
[16:06:39] [Render thread/INFO]: Started 6 worker threads
[16:06:39] [Render thread/INFO]: [bclib] Sending hello to server.
[16:06:39] [Server thread/INFO]: [bclib] Received Hello from Client. (server=2.1.3, client=2.1.3)
[16:06:39] [Server thread/INFO]: [bclib] Auto-Sync is disabled for Singleplayer worlds.
[16:06:39] [Render thread/INFO]: Synced supplementaries-common.json configs
[16:06:39] [Render thread/INFO]: Synced Flute Songs
[16:06:39] [Render thread/INFO]: Synced Captured Mobs settings
[16:06:39] [Render thread/INFO]: Synced Globe data
```

### Other mods

(My mod folder is too big to be put here, so I'll just make a list.)
All Sided Blocks 1.0.1
Another Furniture (fabric) 2.1.2
Architectury 6.3.56
Bad Packets (fabric) 0.2.1
BCLib 2.1.3
Better Nether 7.1.2
Charm (fabric) 4.4.4
Chisel Refabricated 1.4.7
Cloth Config 8.2.88
Continuity 2.0.1
Create (fabric) 0.5.0g-791
Cull Leaves 3.0.1
Dynamic FPS 2.2.0
Enhanced Block Entities 0.7.2
Fabric Language Kotlin 1.8.6
Farmer's Delight (fabric) 1.3.9
Harvest Season 1.2.1
Indium 1.0.9
Lithium 0.10.2
Memory Leak Fix 0.7.0
Missing Wilds 1.1.2
Mod Menu 4.1.1
Moonlight API 2.1.10
More Culling 0.10.0
Mythic Metals 0.16.3
OWO Lib 0.9.0
Patchouli 1.19.2-77
Revelationary 1.0.2
Roughly Enough Items 9.1.572
Smooth Boot 1.7.1
Sodium 0.4.4+build.18
Spectrum 1.6.2 Leisure Time
Supplementaries 2.2.21
TerraBlender 2.0.1.130
Things 0.2.20 
Trinkets 3.4.1
Alloy Forgery 2.0.17
WTHIT 5.13.4
Xaero's Minimap 22.16.2
Xaero's World Map 1.28.3

### Additional Information

![2022-11-25_16 06 50](https://user-images.githubusercontent.com/87100678/204056358-4e8e71cb-1c92-408e-9ec2-5e240578e1d0.png)
Other than this bug, the mod works fine for me. The bug is also probably not caused by mod incompatibility.

**Comment by MBatt1** [comment] 2022-11-28 14:57
Duplicate of #710

**Closed as completed** 2022-12-06 01:25 UTC
Labels: Bug, duplicate, Resolved
