### ISSUE TITLE
Bug: [Render thread/ERROR] No data fixer registered for ...

### ISSUE THREAD

**Issue by davidalb97** [devs-immortal/The-Aether#501] opened 2021-10-02 14:24 UTC
### What happened?

I was looking for errors on the log and found several [Render thread/ERROR] errors.

### Version

1.5.0 (Latest)

### Fabric API Version

0.40.1

### Trinkets Version

3.0.4

### Relevant log output

```shell
[15:18:52] [Render thread/ERROR]: No data fixer registered for aechor_plant
[15:18:52] [Render thread/ERROR]: No data fixer registered for flying_cow
[15:18:52] [Render thread/ERROR]: No data fixer registered for aerbunny
[15:18:52] [Render thread/ERROR]: No data fixer registered for moa
[15:18:52] [Render thread/ERROR]: No data fixer registered for phyg
[15:18:52] [Render thread/ERROR]: No data fixer registered for sheepuff
[15:18:52] [Render thread/ERROR]: No data fixer registered for cockatrice
[15:18:52] [Render thread/ERROR]: No data fixer registered for chest_mimic
[15:18:52] [Render thread/ERROR]: No data fixer registered for golden_dart
[15:18:52] [Render thread/ERROR]: No data fixer registered for enchanted_dart
[15:18:52] [Render thread/ERROR]: No data fixer registered for poison_dart
[15:18:52] [Render thread/ERROR]: No data fixer registered for poison_needle
[15:18:52] [Render thread/ERROR]: No data fixer registered for aerwhale
[15:18:52] [Render thread/ERROR]: No data fixer registered for blue_swet
[15:18:52] [Render thread/ERROR]: No data fixer registered for purple_swet
[15:18:52] [Render thread/ERROR]: No data fixer registered for white_swet
[15:18:52] [Render thread/ERROR]: No data fixer registered for golden_swet
```

### Additional Information

I'm using MultiMC.

**Comment by Jack-Papel** [comment] 2021-10-02 17:23
Thanks for reporting! This is a duplicate of #345, and has already been resolved in dev builds.

**Comment by davidalb97** [comment] 2021-10-03 01:53
Sorry for the duplicate! I searched for it on all issues (closed and opened) but found nothing.

**Comment by Azzyypaaras** [comment] 2021-11-27 06:03
Resolved with b1.6.0

**Closed as completed by Azzyypaaras** 2021-11-27 06:03 UTC
Labels: Bug, duplicate, Resolved
