### ISSUE TITLE
Crash: when launching.

### ISSUE THREAD

**Issue by netcore10** [devs-immortal/The-Aether#663] opened 2022-04-23 00:51 UTC
### What were you doing when the crash occured? How can we replicate it?

1. Added it to my modpack, ran then crashed.

### Did it crash the client or server?

Client

### Mod Version

1.6.8

### Fabric API Version

0.51.1

### Crash Report

```Shell
[01:37:49] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.13.3
[01:37:50] [ForkJoinPool-1-worker-8/WARN]: The mod "extraalchemy" contains invalid entries in its mod json:
- Invalid entry in person "contribution" at line 19 column 21
[01:37:50] [main/INFO]: Loading 235 mods:
	- additionalentityattributes 1.0.0+1.18.2 via apoli
	- advanced_reborn 1.0.5
	- ae2 11.0.0-alpha.5
	- ae2wtlib 11.0.0-alpha.2
	- akashictomeoftools 1.2.1
	- ambientsounds 5.0.16
	- animal_feeding_trough 1.0.3+1.18.2
	- apoli 2.3.3 via origins
	- appleskin 2.4.0+mc1.18.2
	- aqupdgrizzly 1.18-1.3
	- arcanus 1.29
	- architectury 4.2.50
	- artifacts 7.0.3+fabric
	- autoconfig1u 3.4.0
	- balm-fabric 3.0.0+0
	- bclib 1.4.3
	- betteranimalsplus 1.18.2-11.0.5
	- betternether 6.1.0
	- bewitchment 1.18-17
	- blossom 1.18.2-1.0.4
	- blue_endless_jankson 1.2.1 via jankson
	- botania 1.18.2-431-FABRIC
	- bushybusiness 1.1.0
	- byg 1.4-RC-10
	- cacao 1.0
	- calio 1.5.1 via apoli
	- camsbackpacks 2.11
	- capybara 1.0.3
	- cardinal-components-base 4.1.4 via pickyourpoison
	- cardinal-components-block 4.0.1 via polymorph
	- cardinal-components-entity 4.1.4 via pickyourpoison
	- cardinal-components-item 4.0.1 via polymorph
	- chiselsandbits 1.2.84
	- chunky 1.2.164
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.2.57
	- cloth-config-lite 2.0.6 via mealapi
	- com_electronwill_night-config_core 3.6.5 via servercore
	- com_electronwill_night-config_toml 3.6.5 via servercore
	- com_eliotlash_mclib_mclib 18 via geckolib3
	- com_eliotlash_molang_molang 18 via geckolib3
	- com_github_llamalad7_mixinextras 0.0.7 via artifacts
	- com_typesafe_config 1.4.1 via croptopia
	- controlling 9.0+19
	- cooldown-coordinator 0.3.0
	- cpm 0.3.1a
	- crafttweaker 9.1.108
	- creativecore 2.6.10
	- crockpot 0.8.4+1.18.2
	- croptopia 1.8.3
	- crowdin-translate 1.4+1.18.2 via leaves_us_in_peace
	- culinaire 2.4.0
	- cursery 1.18.2-3.0
	- customportalapi 0.0.1-beta50-1.18 via the_aether
	- dawn 3.3.0
	- dimension_data_fix 1.0.1
	- duckling 1.0.3
	- ductwork 0.2.3
	- ecologics 1.5.2
	- edenring 0.4.0
	- endlessocean 0.2.0-BETA
	- entityculling 1.5.1
	- expandability 6.0.0 via artifacts
	- expandedstorage 7.3.12
	- extraalchemy 1.8.0
	- fabric 0.51.1+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric
	- fabric-api-lookup-api-v1 1.6.0+2373a54560 via fabric
	- fabric-biome-api-v1 8.0.4+7b0f312660 via fabric
	- fabric-blockrenderlayer-v1 1.1.12+3ac43d9560 via fabric
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.21+d7c144a860 via fabric
	- fabric-content-registries-v0 3.0.3+d82b939260 via fabric
	- fabric-convention-tags-v1 1.0.1+474e4f7960 via fabric
	- fabric-crash-report-info-v1 0.1.11+3ac43d9560 via fabric
	- fabric-dimensions-v1 2.1.17+2540745460 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.14+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.4.0+4457765560 via fabric
	- fabric-item-groups-v0 0.3.11+91896a4960 via fabric
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric
	- fabric-language-kotlin 1.7.4+kotlin.1.6.21
	- fabric-language-scala 1.1.0+scala.2.13.6
	- fabric-lifecycle-events-v1 2.0.3+2d83e92c60 via fabric
	- fabric-loot-tables-v1 1.0.11+d7c144a860 via fabric
	- fabric-mining-level-api-v1 2.1.0+81ea5b3c60 via fabric
	- fabric-models-v0 0.3.6+d7c144a860 via fabric
	- fabric-networking-api-v1 1.0.21+d882b91560 via fabric
	- fabric-networking-v0 0.3.8+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.1.0+fe4ddef060 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT via bewitchment
	- fabric-registry-sync-v0 0.9.8+0d9ab37260 via fabric
	- fabric-renderer-api-v1 0.4.13+d882b91560 via fabric
	- fabric-renderer-indigo 0.5.0+7faf0d8860 via fabric
	- fabric-renderer-registries-v1 3.2.11+b4f4f6cd60 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-rendering-v0 1.1.13+b4f4f6cd60 via fabric
	- fabric-rendering-v1 1.10.7+54e5b2ec60 via fabric
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric
	- fabric-resource-loader-v0 0.4.18+2de5574560 via fabric
	- fabric-screen-api-v1 1.0.10+d882b91560 via fabric
	- fabric-screen-handler-api-v1 1.2.0+1f6558e860 via fabric
	- fabric-textures-v0 1.0.12+3ac43d9560 via fabric
	- fabric-transfer-api-v1 1.6.0+2373a54560 via fabric
	- fabric-transitive-access-wideners-v1 1.0.0+bd8a4a1860 via fabric
	- fabricenchantments 0.7.2
	- fabricloader 0.13.3
	- fake-player-api 0.3.0 via the_bumblezone
	- farmingforblockheads 10.0.0
	- faux-custom-entity-data 2.0.1
	- feature_nbt_deadlock_be_gone 2.0.0+1.18.2-rc1
	- fiber 0.23.0-2 via botania
	- fishofthieves 1.0.5
	- fixedwaterlogging 1.0.2
	- fluidtank 18.4.476-fabric
	- foodplusid 1.3.1
	- freecam 1.0.4
	- friendsandfoes 1.3.4
	- gearreborn 1.18.2-0.1.11
	- geckolib3 3.0.38
	- go-fish 1.5.0-1.18.2
	- graveyard 1.7
	- graveyard_biomes 1.1
	- gud_recipe_confidence 1.0.2 via the_aether
	- harvest-with-ease-fabric 1.2.0
	- iconicwands 1.0.4
	- impersonate 2.4.1 via bewitchment
	- incubus_core 1.6.6+1.18.2 via the_aether
	- indium 1.0.2+mc1.18.2
	- ingredient-extension-api 2.0.5
	- inventoryprofilesnext 1.3.5
	- io_leangen_geantyref_geantyref 1.3.11 via croptopia
	- iris 1.2.2-build.32
	- jamfabric 1.3.4
	- jankson 4.0.0+j1.2.0 via libgui
	- java 17
	- kanos_config 0.2.0+1.14.4-1.19 via pehkui
	- lazydfu 0.1.2
	- leaves_us_in_peace 1.0.4
	- libblockattributes 0.10.2
	- libblockattributes_core 0.10.2 via libblockattributes
	- libblockattributes_fluids 0.10.2 via libblockattributes
	- libblockattributes_items 0.10.2 via libblockattributes
	- libgui 5.0.0-beta.2+1.18-rc1 via stendhal
	- libninepatch 1.1.0 via libgui
	- lithium 0.7.9
	- llamarama 1.6.4
	- lovely_snails 1.0.4+1.18
	- lushforest 1.3.0
	- mavm 1.0.7a
	- mealapi 0.3+1.18
	- megaparrot 1.0.4
	- minecraft 1.18.2
	- modid 1.0.0
	- modmenu 3.1.1
	- moretags 3.0.3 via the_aether
	- naturescompass 1.18.2-2.0.3-fabric
	- nears 1.1.8
	- ninjaphenix_container_lib 1.3.0
	- notenoughcrashes 4.1.6+1.18.2
	- observable 2.2.3
	- omega-config 1.2.3-1.18.1 via qolfixes
	- org_anarres_jcpp 1.4.14 via iris
	- org_javassist_javassist 3.28.0-GA via crafttweaker
	- org_jetbrains_kotlin_kotlin-reflect 1.6.21 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.21 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.21 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.21 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.2 via fabric-language-kotlin
	- org_joml_joml 1.10.2 via sodium
	- org_json_json 20211205 via pickyourpoison
	- org_reflections_reflections 0.10.2 via crafttweaker
	- org_spongepowered_configurate-core 4.1.2 via croptopia
	- org_spongepowered_configurate-hocon 4.1.2 via croptopia
	- origins 1.4.1
	- overweight_farming 1.18.2-1.2.0-fabric
	- patchouli 1.18.2-67-FABRIC
	- pehkui 3.2.2+1.14.4-1.19
	- phosphor 0.8.1
	- pickyourpoison 1.0.5
	- placeholder-api 1.1.3+1.17.1 via styledchat
	- playerabilitylib 1.5.0 via bewitchment
	- plutoscoffee 1.18.2-1.9
	- polymorph 0.0.20-1.18.2
	- pugh_lib 1.3.0 via veggie_way
	- qolfixes 1.4
	- reach-entity-attributes 2.1.1 via bewitchment
	- reborncore 5.2.0-beta.2
	- reinfbarrel 2.0.0+1.18
	- reinfcore 2.0.0+1.18 via reinfbarrel
	- roughlyenoughitems 8.1.449
	- roughlyenoughresources 2.5.0
	- runes 1.1.0
	- sandwichmod fabric-1.18.2-v2.0.1
	- satin 1.7.2 via the_aether
	- servercore 1.2.8-1.18.2
	- skylorlib 1.2.3
	- slotlink 4.3.1
	- smoothboot 1.18.2-1.7.0
	- sodium 0.4.1+build.15
	- someforgepatchesported 1.0.3
	- spark 1.8.14
	- spellbound 1.8.0
	- sprout 1.1.0
	- stendhal 1.2.0-1.18
	- step-height-entity-attribute 1.0.0 via artifacts
	- styledchat 1.2.3+1.18
	- sushimod fabric-1.18.2-v1.0.1
	- team_reborn_energy 2.2.0 via reborncore
	- techreborn 5.2.0-beta.2
	- terrablender 1.1.0.99
	- terraform-wood-api-v1 3.0.0 via bewitchment
	- the_aether 1.6.8+1.18.2
	- the_bumblezone 5.0.10+1.18.2
	- trinkets 3.3.0
	- vanilla_degus 1.3.0
	- variantbarrels 1.4.0
	- veggie_way 1.2.32
	- villainousfishai 1.1
	- vmp 0.2.0+beta.3.17
	- voicechat 1.18.2-2.2.35
	- wildlife 1.18.2-1.0
	- wmitaf 2.2.0
	- world_of_food 1.0.1
	- wthit 4.8.1
[01:37:51] [main/WARN]: Mod `cpm` (0.3.1a) does not respect SemVer - comparison support is limited.
[01:37:51] [main/WARN]: Mod `mavm` (1.0.7a) does not respect SemVer - comparison support is limited.
[01:37:51] [main/WARN]: Mod `sandwichmod` (fabric-1.18.2-v2.0.1) does not respect SemVer - comparison support is limited.
[01:37:51] [main/WARN]: Mod `sushimod` (fabric-1.18.2-v1.0.1) does not respect SemVer - comparison support is limited.
[01:37:51] [main/WARN]: Mod `terrablender` (1.1.0.99) uses more dot-separated version components than SemVer allows; support for this is currently not guaranteed.
[01:37:51] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/netco/Documents/Curse/Minecraft/Install/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[01:37:51] [main/INFO]: Compatibility level set to JAVA_17
[01:37:52] [main/WARN]: Reference map 'ecologics-refmap.json' for ecologics.mixins.json could not be read. If this is a development environment you can ignore this message
[01:37:52] [main/ERROR]: 
[01:37:52] [main/ERROR]: 
[01:37:52] [main/ERROR]: 
[01:37:52] [main/ERROR]: 
[01:37:52] [main/ERROR]: bclib is incompatible with RecipeConfidence.
[01:37:52] [main/ERROR]: 
[01:37:52] [main/ERROR]: There is a chance that the compatibility layer is not correct, issues may arise
[01:37:52] [main/ERROR]: when using recipes (crafting, smelting, etc.) because of the conflict.
[01:37:52] [main/ERROR]: 
[01:37:52] [main/ERROR]: If you are the authors of bclib and have validated the compatibility layer, feel
[01:37:52] [main/ERROR]: free to make a mixin that changes BclibFlag.bclibCompatValidated to return true.
[01:37:52] [main/ERROR]: 
[01:37:52] [main/ERROR]: 
[01:37:52] [main/ERROR]: 
[01:37:52] [main/ERROR]: 
[01:37:52] [main/INFO]: Loaded configuration file for Lithium: 100 options available, 2 override(s) found
[01:37:52] [main/WARN]: [Satin] Sodium is present, custom block renders may not work
[01:37:52] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 1 override(s) found
[01:37:52] [main/WARN]: Reference map 'wildlife-refmap.json' for wildlife.mixins.json could not be read. If this is a development environment you can ignore this message
[01:37:54] [main/WARN]: Force-disabling mixin 'alloc.chunk_ticking.ServerChunkManagerMixin' as rule 'mixin.alloc.chunk_ticking' (added by mods [servercore]) disables it and children
[01:37:54] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [vmp]) disables it and children
[01:37:54] [main/WARN]: Error loading class: net/kyrptonaught/inventorysorter/client/SortButtonWidget (java.lang.ClassNotFoundException: net/kyrptonaught/inventorysorter/client/SortButtonWidget)
[01:37:54] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[01:37:54] [main/WARN]: Error loading class: carpet/patches/EntityPlayerMPFake (java.lang.ClassNotFoundException: carpet/patches/EntityPlayerMPFake)
[01:37:55] [main/INFO]: Trying to switch memory allocators to work around memory leaks present with Jemalloc 5.0.0 through 5.2.0 on Windows
[01:37:55] [main/INFO]: Smooth Boot config initialized
[01:37:57] [main/WARN]: @Final field field_22786:Ljava/util/List; in mixins.ipnext.json:MixinScreen should be final
[01:37:57] [main/WARN]: @Final field field_33815:Ljava/util/List; in mixins.ipnext.json:MixinScreen should be final
[01:37:58] [main/WARN]: Error loading class: org/spongepowered/asm/synthetic/args/Args$1 (java.lang.ClassNotFoundException: org/spongepowered/asm/synthetic/args/Args$1)
[01:38:01] [main/WARN]: @Redirect conflict. Skipping moretags.mixins.json:item.shears.PumpkinBlockMixin->@Redirect::onUse$ItemStack$isOf(Lnet/minecraft/class_1799;Lnet/minecraft/class_1792;)Z from mod moretags with priority 1000, already redirected by bclib.mixins.common.json:shears.PumpkinBlockMixin->@Redirect::bn_useProxy(Lnet/minecraft/class_1799;Lnet/minecraft/class_1792;)Z from mod bclib with priority 1000
[01:38:01] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:418) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.world.gen.carver.CarverConfig.method_33968(CarverConfig:16) ~[?:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.1.27.jar:?]
	at net.minecraft.world.gen.carver.CarverConfig.<clinit>(CarverConfig:12) ~[?:?]
	at net.minecraft.world.gen.carver.Carver.<clinit>(Carver:33) ~[?:?]
	at net.minecraft.world.gen.carver.ConfiguredCarvers.<clinit>(ConfiguredCarvers:19) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30572(BuiltinRegistries:52) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30566(BuiltinRegistries:86) ~[?:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.<clinit>(BuiltinRegistries:85) ~[?:?]
	at net.minecraft.util.registry.Registry.<clinit>(Registry:291) ~[?:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap:49) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:153) ~[fabric-loader-0.13.3-1.18.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2445 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.world.gen.carver.CarverDebugConfig.<clinit>(CarverDebugConfig:9) ~[?:?]
	at net.minecraft.world.gen.carver.CarverConfig.method_33968(CarverConfig:16) ~[?:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.1.27.jar:?]
	at net.minecraft.world.gen.carver.CarverConfig.<clinit>(CarverConfig:12) ~[?:?]
	at net.minecraft.world.gen.carver.Carver.<clinit>(Carver:33) ~[?:?]
	at net.minecraft.world.gen.carver.ConfiguredCarvers.<clinit>(ConfiguredCarvers:19) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30572(BuiltinRegistries:52) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30566(BuiltinRegistries:86) ~[?:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.<clinit>(BuiltinRegistries:85) ~[?:?]
	at net.minecraft.util.registry.Registry.<clinit>(Registry:291) ~[?:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap:49) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:153) ~[fabric-loader-0.13.3-1.18.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.world.gen.carver.CarverDebugConfig.<clinit>(CarverDebugConfig:9) ~[?:?]
	at net.minecraft.world.gen.carver.CarverConfig.method_33968(CarverConfig:16) ~[?:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.1.27.jar:?]
	at net.minecraft.world.gen.carver.CarverConfig.<clinit>(CarverConfig:12) ~[?:?]
	at net.minecraft.world.gen.carver.Carver.<clinit>(Carver:33) ~[?:?]
	at net.minecraft.world.gen.carver.ConfiguredCarvers.<clinit>(ConfiguredCarvers:19) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30572(BuiltinRegistries:52) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30566(BuiltinRegistries:86) ~[?:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.<clinit>(BuiltinRegistries:85) ~[?:?]
	at net.minecraft.util.registry.Registry.<clinit>(Registry:291) ~[?:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap:49) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:153) ~[fabric-loader-0.13.3-1.18.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector onUse$ItemStack$isOf(Lnet/minecraft/class_1799;Lnet/minecraft/class_1792;)Z in moretags.mixins.json:item.shears.PumpkinBlockMixin from mod moretags failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap MoreTags-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.world.gen.carver.CarverDebugConfig.<clinit>(CarverDebugConfig:9) ~[?:?]
	at net.minecraft.world.gen.carver.CarverConfig.method_33968(CarverConfig:16) ~[?:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.1.27.jar:?]
	at net.minecraft.world.gen.carver.CarverConfig.<clinit>(CarverConfig:12) ~[?:?]
	at net.minecraft.world.gen.carver.Carver.<clinit>(Carver:33) ~[?:?]
	at net.minecraft.world.gen.carver.ConfiguredCarvers.<clinit>(ConfiguredCarvers:19) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30572(BuiltinRegistries:52) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30566(BuiltinRegistries:86) ~[?:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.<clinit>(BuiltinRegistries:85) ~[?:?]
	at net.minecraft.util.registry.Registry.<clinit>(Registry:291) ~[?:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap:49) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:153) ~[fabric-loader-0.13.3-1.18.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 2 more
```

### Other mods

Couldn't upload zip here directly. Here's a google drive link.

[`Google Drive link`](https://drive.google.com/file/d/1pny4sokUqd0-91yHx6RjOBlL3grMuVNE/view?usp=sharing)

**Comment by Jack-Papel** [comment] 2022-04-23 01:14
Thanks for reporting. This should be fixed in the next update

**Comment by Jack-Papel** [comment] 2022-05-01 02:51
This will not be fixed in the next update, but we are discussing a solution. Duplicate of #664

**Comment by MBatt1** [comment] 2022-11-07 18:59
BClib issues, duplicate of #664, please post to that thread if you continue to have issues with the latest version

**Closed as completed by MBatt1** 2022-11-07 18:59 UTC
Labels: Bug, duplicate
