### ISSUE TITLE
Bug: Some 'EntryPoint' crash.

### ISSUE THREAD

**Issue by MagmaSlime123** [devs-immortal/The-Aether#682] opened 2022-05-26 19:06 UTC
### What happened?

See title.

To replicate:
Install the mod and start the game.

### Mod Version

1.6.9

### Fabric API Version

0.53.4

### Relevant log output

https://pastebin.com/504afjvh (Logs file)
https://pastebin.com/KtmwcWm8 (Crash Report file)

### Other mods

Crash reports come with modlists in them. Thank Fabric for this. See above for the logs and crash report.

### Additional Information

N/A

**Comment by Jack-Papel** [comment] 2022-05-26 19:10
Thanks for reporting! This is a duplicate of #667

**Comment by MagmaSlime123** [comment] 2022-05-26 20:09
Ah, sorry.

**Closed as completed** 2022-05-29 22:04 UTC
Labels: Bug, duplicate, Incompatibility
